### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by janheinrichmerker** [wichtounet/sudoku_dataset#1]
From the Readme and the file tree it is not obvious under which license the dataset is released.
I would appreciate if you take the time to [choose an appropriate license](https://choosealicense.com/).

**Comment by wichtounet** [comment]
I do not know about non-software licenses. 

Would CC-BY-4.0 work?

**Comment by janheinrichmerker** [comment]
Any CC license can perfectly be used for your dataset, as I see it. That may have complications with the source code, as CC is generally not meant for code.
I would suggest releasing the code under MIT oder Apache license and the dataset itself under CC.

**Comment by janheinrichmerker** [comment]
See this copyright notice for reference:
https://github.com/github/choosealicense.com/blob/gh-pages/README.md#license

**Comment by wichtounet** [comment]
I have set the license in https://github.com/wichtounet/sudoku_dataset/commit/0134b17499769145401bafa0de31729e7bc0b16a
